package generator

const (
	// ヘッダーテンプレート
	headerTemplate = `; ========================================
; Generated by ttlx %s
; Source: %s
; Generated at: %s
; ========================================

`

	// 変数定義テンプレート
	variablesTemplate = `; === Variables ===
timeout = %d

`

	// 接続テンプレート（最初のステップ）
	connectTemplate = `; === Step %d: %s ===
:CONNECT_%s
connect '%s:%d /ssh /auth=%s /user=%s%s%s'
if result <> 2 then
    goto ERROR_CONNECT_%s
endif
wait '%s'
if result = 0 then
    goto TIMEOUT_%s
endif

`

	// SSH コマンドテンプレート（2番目以降のステップ）
	sshTemplate = `; === Step %d: %s ===
sendln 'ssh %s@%s -p %d'
wait 'password:'
if result = 0 then
    goto TIMEOUT_%s
endif

`

	// パスワード認証テンプレート（環境変数）
	passwordEnvTemplate = `; Password authentication (from environment)
getenv '%s' password
sendln password

`

	// パスワード認証テンプレート（実行時入力）
	passwordPromptTemplate = `; Password authentication (prompt)
passwordbox 'Enter password for %s:' 'password'
sendln password

`

	// パスワード認証テンプレート（直接指定）
	passwordValueTemplate = `; Password authentication
sendln '%s'

`

	// コマンド実行テンプレート
	commandTemplate = `; Command: %s
sendln '%s'
wait '%s'
if result = 0 then
    goto TIMEOUT_%s
endif

`

	// 成功終了テンプレート
	successTemplate = `:SUCCESS
closett
end

`

	// エラーハンドリングテンプレート（接続失敗）
	errorConnectTemplate = `:ERROR_CONNECT_%s
messagebox 'Failed to connect to %s' 'Error'
goto CLEANUP

`

	// エラーハンドリングテンプレート（タイムアウト）
	errorTimeoutTemplate = `:TIMEOUT_%s
messagebox 'Connection timeout: %s' 'Error'
goto CLEANUP

`

	// クリーンアップテンプレート
	cleanupTemplate = `:CLEANUP
closett
end
`
)
