package generator

const (
	// ヘッダーテンプレート
	headerTemplate = `; ========================================
; Generated by ttlx %s
; Source: %s
; Route: %s
; Generated at: %s
; ========================================

`

	// 変数定義テンプレート
	variablesTemplate = `; === Variables ===
timeout = %d

`

	// 接続テンプレート（最初のステップ）
	connectTemplate = `; === Step %d: %s ===
:CONNECT_%s
connect '%s:%d /ssh /auth=%s /user=%s%s%s'
if result <> 2 then
    goto ERROR_CONNECT_%s
endif
wait '%s'
if result = 0 then
    goto TIMEOUT_%s
endif

`

	// SSH コマンドテンプレート（2番目以降のステップ）
	sshTemplate = `; === Step %d: %s ===
sendln 'ssh %s@%s -p %d'
wait '%s'
if result = 0 then
    goto TIMEOUT_%s
endif

`

	// パスワード認証テンプレート（直接指定）
	passwordValueTemplate = `; Password authentication
sendln '%s'

`

	// パスワード認証テンプレート（パスワードファイル - 第1ステップ）
	passwordFileConnectTemplate = `; === Step %d: %s ===
:CONNECT_%s
; Password authentication (from password file)
getpassword '%s' '%s' password

; Build connect command with password
strconcat connectcmd '%s:%d /ssh /auth=%s /user=%s%s /passwd='
strconcat connectcmd password
connect connectcmd
if result <> 2 then
    goto ERROR_CONNECT_%s
endif
wait '%s'
if result = 0 then
    goto TIMEOUT_%s
endif

`

	// パスワード認証テンプレート（パスワードファイル - 第2ステップ以降）
	passwordFileTemplate = `; Password authentication (from password file)
getpassword '%s' '%s' password
sendln password

`

	// コマンド実行テンプレート
	commandTemplate = `; Command: %s
sendln '%s'
wait '%s'
if result = 0 then
    goto TIMEOUT_%s
endif

`

	// 成功終了テンプレート（接続保持）
	successKeepAliveTemplate = `; === Success (Keep connection alive) ===
:SUCCESS
end

`

	// 成功終了テンプレート（自動切断）
	successTemplate = `:SUCCESS
closett
end

`

	// エラーハンドリングテンプレート（接続失敗）
	errorConnectTemplate = `:ERROR_CONNECT_%s
messagebox 'Failed to connect to %s' 'Error'
goto CLEANUP

`

	// エラーハンドリングテンプレート（タイムアウト）
	errorTimeoutTemplate = `:TIMEOUT_%s
messagebox 'Connection timeout: %s' 'Error'
goto CLEANUP

`

	// クリーンアップテンプレート
	cleanupTemplate = `:CLEANUP
closett
end
`
)
